# apiVersion: v1
# kind: Service
# metadata:
#   name: twilio
#   labels:
#     app: twilio
# spec:
#   type: LoadBalancer
#   ports:
#     - name: twilio
#       port: 80
#       targetPort: 5000
#   selector:
#     app: twilio

apiVersion: v1
kind: Service
metadata:
  name: workshop
  namespace: denotes
  labels:
    app: workshop
spec:
  type: NodePort
  ports:
    - name: workshop
      port: 80
      targetPort: 3000
      nodePort: 30095  # Specify the desired nodePort value here
  selector:
    app: workshop
